### ISSUE TITLE
Fatal error: Object::add_extension() - Can't find extension class for "GoogleSitemapSiteTreeExtension"

### ISSUE THREAD

**Issue by CMeldgaard** [i-lateral/silverstripe-googleshoppingfeed#7]
Module tries to add the GoogleSitemapSiteTreeExtension, but the extensions doesnt exist

**Comment by mlewis-everley** [comment]
I am guessing this is for SS3? If so, I just pushed up an update that removes that call (it should not be needed).

Can you see if that works @CMeldgaard ?
